import type { CitySlug } from "@/content/cities";

export type ProjectCity = {
  slug: string;
  name: string;
  province: string;
  coverageCitySlug: CitySlug;
  summary: string;
  seoFocus: string;
};

export type ProjectNeighborhood = {
  slug: string;
  name: string;
  projectCitySlug: string;
  coverageCitySlug: CitySlug;
  focus: string;
  marketCategory: string;
  demandSignals: string[];
};

export const projectCities: ProjectCity[] = [
  {
    slug: "tehran",
    name: "تهران",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "خوشه اصلی نوسازی، برج‌سازی، پروژه‌های اداری، تجاری، صنعتی و بازسازی شهری پرشین‌سازه در تهران.",
    seoFocus: "پروژه‌های در حال ساخت تهران، محله‌های فعال ساختمانی تهران، فروش بین‌شرکتی به سازندگان تهران",
  },
  {
    slug: "karaj",
    name: "کرج",
    province: "استان البرز",
    coverageCitySlug: "karaj",
    summary: "خوشه پروژه‌های مسکونی، صنعتی، ویلایی و نوسازی پرتراکم در کرج و کریدورهای اطراف آن.",
    seoFocus: "پروژه‌های در حال ساخت کرج، محله‌های فعال ساختمانی کرج، تامین مصالح و تجهیزات در کرج",
  },
  {
    slug: "lavasan",
    name: "لواسان",
    province: "استان تهران",
    coverageCitySlug: "lavasan",
    summary: "خوشه ویلاسازی و ساخت سفارشی لوکس در لواسان و بازارهای نزدیک به شمیرانات.",
    seoFocus: "پروژه‌های ویلایی لواسان، ساخت‌وساز لوکس لواسان، تامین‌کنندگان ویلا و متریال لوکس",
  },
  {
    slug: "damavand",
    name: "دماوند",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار ویلاهای کوهستانی، باغ‌ویلا، ساخت سردسیر و پروژه‌های حومه شرقی تهران.",
    seoFocus: "پروژه‌های ویلایی دماوند، ساخت‌وساز آبسرد و گیلاوند، تامین متریال ضدیخ و گرمایش مستقل",
  },
  {
    slug: "shemiranat",
    name: "شمیرانات",
    province: "استان تهران",
    coverageCitySlug: "lavasan",
    summary: "خوشه ساخت‌وساز ویلایی، کوهستانی و لوکس در فشم، میگون و محورهای شمال شرق تهران.",
    seoFocus: "پروژه‌های ویلایی شمیرانات، ساخت‌وساز فشم و میگون، تامین‌کنندگان ویلاهای کوهستانی",
  },
  {
    slug: "pardis",
    name: "پردیس",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار ترکیبی مسکن انبوه، تکمیل پروژه‌های شهری و ساختمان‌های فناورانه شرق تهران.",
    seoFocus: "پروژه‌های در حال ساخت پردیس، مسکن انبوه پردیس، ساختمان‌های فناوری پردیس",
  },
  {
    slug: "parand",
    name: "پرند",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "خوشه انبوه‌سازی اقتصادی و پروژه‌های تکرارشونده در کریدور جنوب غرب تهران.",
    seoFocus: "پروژه‌های در حال ساخت پرند، تامین مصالح مسکن انبوه، ساخت‌وساز شهر جدید پرند",
  },
  {
    slug: "eslamshahr",
    name: "اسلامشهر",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار توسعه مسکونی-صنعتی، نوسازی سریع و تامین میان‌رده در جنوب غرب تهران.",
    seoFocus: "پروژه‌های ساختمانی اسلامشهر، ساخت‌وساز احمدآباد مستوفی، تامین مصالح میان‌رده",
  },
  {
    slug: "pakdasht",
    name: "پاکدشت",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "خوشه لجستیک سنگین، مراکز توزیع، کارخانه و پروژه‌های صنعتی شرق و جنوب شرق تهران.",
    seoFocus: "پروژه‌های صنعتی پاکدشت، ساخت مراکز لجستیک خاوران، کف صنعتی و سقف صنعتی",
  },
  {
    slug: "kahrizak",
    name: "کهریزک",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار انبار، سردخانه، لجستیک، retrofit صنعتی و امنیت کالا در جنوب تهران.",
    seoFocus: "پروژه‌های انبار کهریزک، ساخت‌وساز شورآباد، مراکز لجستیکی جنوب تهران",
  },
  {
    slug: "shamsabad",
    name: "شمس‌آباد",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "خوشه سوله‌های بزرگ، کف صنعتی، برق صنعتی و زیرساخت تولید در شهرک صنعتی شمس‌آباد.",
    seoFocus: "پروژه‌های صنعتی شمس‌آباد، سوله سازی شمس‌آباد، کف صنعتی و برق صنعتی کارخانه",
  },
  {
    slug: "safadasht",
    name: "صفادشت",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار توسعه کارخانه، سوله، کف صنعتی، تابلو برق و زیرساخت تولید در شهرک صنعتی صفادشت.",
    seoFocus: "پروژه‌های شهرک صنعتی صفادشت، سوله صفادشت، کف صنعتی و تاسیسات کارخانه",
  },
  {
    slug: "hashtgerd",
    name: "هشتگرد و مهستان",
    province: "استان البرز",
    coverageCitySlug: "karaj",
    summary: "خوشه انبوه‌سازی، شهر جدید، پروژه‌های مسکونی اقتصادی و ویلاهای پیرامونی غرب البرز.",
    seoFocus: "پروژه‌های ساختمانی هشتگرد، ساخت‌وساز مهستان، تامین مصالح انبوه‌سازی",
  },
  {
    slug: "andisheh",
    name: "اندیشه",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار توسعه برنامه‌ریزی‌شده، مسکن میان‌رده، ویلاشهر و سفارش‌های حجمی غرب تهران.",
    seoFocus: "پروژه‌های در حال ساخت اندیشه، مسکن انبوه اندیشه، تامین مصالح حجمی",
  },
  {
    slug: "kordan",
    name: "کردان",
    province: "استان البرز",
    coverageCitySlug: "karaj",
    summary: "بازار ویلاهای تفریحی، استخر، محوطه‌سازی، automation و مصالح outdoor غرب کرج.",
    seoFocus: "پروژه‌های ویلایی کردان، ساخت باغ ویلا کردان، تامین استخر و محوطه‌سازی",
  },
  {
    slug: "chaharbagh",
    name: "چهارباغ",
    province: "استان البرز",
    coverageCitySlug: "karaj",
    summary: "خوشه تبدیل باغ به ویلا، استخر، محوطه و تجهیزات بیرونی در غرب کرج.",
    seoFocus: "پروژه‌های ویلایی چهارباغ، ساخت‌وساز رامجین، تامین استخر و landscape",
  },
  {
    slug: "tehrandasht",
    name: "تهراندشت",
    province: "استان البرز",
    coverageCitySlug: "karaj",
    summary: "بازار ویلاهای زمین تخت، استخر، آب‌بندی، محوطه و سیستم‌های ویلایی در البرز.",
    seoFocus: "پروژه‌های ویلایی تهراندشت، ساخت‌وساز سرخاب، تامین استخر و محوطه",
  },
  {
    slug: "roudhen-bomehen",
    name: "رودهن و بومهن",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار ویلاهای میان‌رده و آپارتمان‌های کم‌ارتفاع در کریدور شرقی تهران.",
    seoFocus: "پروژه‌های ساختمانی رودهن، ساخت‌وساز بومهن، عایق‌کاری و گرمایش ویلا",
  },
  {
    slug: "shahr-e-rey",
    name: "شهرری",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "خوشه نوسازی پرتراکم، بافت فرسوده و نماهای اقتصادی قابل اجرا در جنوب تهران.",
    seoFocus: "پروژه‌های ساختمانی شهرری، نوسازی دولت‌آباد، تامین مصالح میان‌رده جنوب تهران",
  },
  {
    slug: "chahardangeh",
    name: "چهاردانگه",
    province: "استان تهران",
    coverageCitySlug: "tehran",
    summary: "بازار نمایشگاه، کارگاه چوب، انبار، حمل کالای حجیم و سازه‌های تجاری-کارگاهی.",
    seoFocus: "پروژه‌های تجاری چهاردانگه، ساخت نمایشگاه یافت‌آباد، کارگاه چوب و باربری",
  },
];

export const projectNeighborhoods: ProjectNeighborhood[] = [
  {
    slug: "abbas-abad-argentina",
    name: "عباس‌آباد / آرژانتین",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "اداری، تجاری، نما و زیرساخت فنی ساختمان",
    marketCategory: "commercial-office",
    demandSignals: ["HVAC اداری", "کرتین‌وال", "شبکه و امنیت", "آسانسور تجاری"],
  },
  {
    slug: "absard-damavand",
    name: "آبسرد دماوند",
    projectCitySlug: "damavand",
    coverageCitySlug: "tehran",
    focus: "تبدیل باغ به ویلا، سرمای شدید، عایق، گرمایش مستقل، متریال outdoor و امنیت دورکار",
    marketCategory: "mountain-villa",
    demandSignals: ["عایق حرارتی", "گرمایش مستقل", "متریال ضدیخ", "امنیت هوشمند"],
  },
  {
    slug: "andisheh",
    name: "شهر جدید اندیشه",
    projectCitySlug: "andisheh",
    coverageCitySlug: "tehran",
    focus: "انبوه‌سازی، توسعه برنامه‌ریزی‌شده و تامین میان‌رده حجمی",
    marketCategory: "mass-housing",
    demandSignals: ["مصالح میان‌رده", "تامین حجمی", "تاسیسات استاندارد", "درب و سرامیک"],
  },
  {
    slug: "azimiyeh",
    name: "عظیمیه",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "لوکس‌سازی کرج، شیب کوهپایه‌ای و نمای ممتاز",
    marketCategory: "premium-residential",
    demandSignals: ["نمای لوکس", "آسانسور ممتاز", "تاسیسات باکیفیت", "اجرای شیب‌دار"],
  },
  {
    slug: "baghestan-shahin-villa",
    name: "باغستان و شاهین‌ویلا کرج",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "نوسازی پرتراکم، affordability میان‌رده و تامین سریع محلی",
    marketCategory: "high-turnover-residential",
    demandSignals: ["مصالح استاندارد", "تکمیل سریع", "آسانسور مسکونی", "لوله‌کشی"],
  },
  {
    slug: "bazaar-baharestan",
    name: "بازار و بهارستان",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "بازسازی تجاری تاریخی، ایمنی حریق و لجستیک محدود",
    marketCategory: "historic-commercial",
    demandSignals: ["ایمنی حریق", "کف پرتردد", "درب امنیتی", "اجرای کم‌مزاحمت"],
  },
  {
    slug: "chaharbagh-ramjin",
    name: "چهارباغ و رامجین",
    projectCitySlug: "chaharbagh",
    coverageCitySlug: "karaj",
    focus: "تبدیل باغ به ویلا، استخر، محوطه‌سازی و تجهیزات بیرونی",
    marketCategory: "villa-corridor",
    demandSignals: ["استخر", "آب‌بندی", "محوطه‌سازی", "متریال outdoor"],
  },
  {
    slug: "chitgar-lake-bamland",
    name: "دریاچه چیتگر و باملند",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "برج‌های lake-view، retail تفریحی، کرتین‌وال و مشاعات لوکس",
    marketCategory: "high-rise-retail",
    demandSignals: ["کرتین‌وال", "HVAC تجاری", "مشاعات لوکس", "استخر و leisure"],
  },
  {
    slug: "chitgar",
    name: "چیتگر",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "برج‌های بلندمرتبه و توسعه انبوه",
    marketCategory: "high-rise-mass-development",
    demandSignals: ["آسانسور پرتردد", "تاسیسات حجمی", "نما", "مصالح انبوه"],
  },
  {
    slug: "damavand-gilavand",
    name: "دماوند / گیلاوند",
    projectCitySlug: "damavand",
    coverageCitySlug: "tehran",
    focus: "ویلاسازی حومه‌ای، اقلیم کوهستانی و امنیت مستقل",
    marketCategory: "suburban-villa",
    demandSignals: ["عایق اقلیمی", "گرمایش مستقل", "CCTV", "محوطه‌سازی"],
  },
  {
    slug: "darrous-gheytarieh",
    name: "دروس و قیطریه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی لوکس آرام، آکوستیک و فینیشینگ بوتیک",
    marketCategory: "boutique-luxury-infill",
    demandSignals: ["عایق صوتی", "HVAC کم‌صدا", "فینیشینگ بوتیک", "پنجره باکیفیت"],
  },
  {
    slug: "ekbatan-apadana",
    name: "اکباتان و آپادانا",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی عمیق مگابلاک، تاسیسات، آسانسور، رایزر، مشاعات و بهره‌برداری",
    marketCategory: "mega-block-retrofit",
    demandSignals: ["نوسازی آسانسور", "HVAC جایگزین", "رایزر", "مشاعات"],
  },
  {
    slug: "elahiye",
    name: "الهیه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "گودبرداری عمیق، فضای محدود و اینفیل فوق‌لوکس",
    marketCategory: "ultra-premium-infill",
    demandSignals: ["پایدارسازی گود", "متریال لوکس", "آسانسور VIP", "BMS"],
  },
  {
    slug: "eslamshahr-ahmadabad-mostoufi",
    name: "اسلامشهر و احمدآباد مستوفی",
    projectCitySlug: "eslamshahr",
    coverageCitySlug: "tehran",
    focus: "توسعه سریع، بافت مسکونی-صنعتی و تامین میان‌رده حجمی",
    marketCategory: "urban-expansion",
    demandSignals: ["مصالح میان‌رده", "تامین سریع", "پروژه‌های ترکیبی", "تاسیسات استاندارد"],
  },
  {
    slug: "fardis",
    name: "فردیس",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "ساخت انبوه، تراکم بالا و تامین اقتصادی حجمی",
    marketCategory: "mass-market-density",
    demandSignals: ["مصالح اقتصادی", "آسانسور پایه", "درب استاندارد", "لوله‌کشی حجمی"],
  },
  {
    slug: "farmanieh-kamranieh",
    name: "فرمانیه و کامرانیه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "امنیت سطح بالا، پلاک‌های لوکس و مشاعات ممتاز",
    marketCategory: "embassy-grade-luxury",
    demandSignals: ["امنیت پیشرفته", "نمای سنگی", "استخر و gym", "smart home"],
  },
  {
    slug: "fasham-meygoun",
    name: "فشم و میگون",
    projectCitySlug: "shemiranat",
    coverageCitySlug: "lavasan",
    focus: "ویلاسازی کوهستانی، شیب شدید، سرما و مصالح مقاوم",
    marketCategory: "mountain-villa",
    demandSignals: ["دیوار حائل", "عایق سردسیر", "گرمایش سنگین", "زهکشی شیب"],
  },
  {
    slug: "fath-highway-shadabad",
    name: "بزرگراه فتح و شادآباد",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "سوله، انبار، کف صنعتی، سقف صنعتی و retrofit کارگاهی",
    marketCategory: "industrial-warehouse",
    demandSignals: ["کف صنعتی", "سقف سوله", "برق صنعتی", "تهویه صنعتی"],
  },
  {
    slug: "garmdarreh",
    name: "گرمدره",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "توسعه مرزی، برج‌سازی مسکونی و تامین حجمی میان‌رده",
    marketCategory: "border-mass-development",
    demandSignals: ["بتن و فولاد", "فینیشینگ میان‌رده", "تاسیسات حجمی", "آسانسور"],
  },
  {
    slug: "gisha-kouy-e-nasr",
    name: "گیشا و کوی نصر",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "بافت شبکه‌ای، نوسازی متراکم، خیابان‌های محدود، پارکینگ مکانیزه و retail محلی",
    marketCategory: "dense-urban-redevelopment",
    demandSignals: ["پارکینگ مکانیزه", "آسانسور", "fit-out تجاری", "لوله‌کشی"],
  },
  {
    slug: "gohardasht",
    name: "گوهردشت",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "بازسازی تجاری-مسکونی و تامین حجمی میان‌رده تا بالارده",
    marketCategory: "mixed-use-redevelopment",
    demandSignals: ["storefront", "مصالح میان‌رده", "آسانسور", "HVAC"],
  },
  {
    slug: "golshahr-kianmehr",
    name: "گلشهر و کیانمهر کرج",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "آپارتمان‌سازی میان‌رده، نوسازی سریع و فینیشینگ حجمی",
    marketCategory: "mid-market-residential",
    demandSignals: ["فینیشینگ حجمی", "درب و سرامیک", "HVAC استاندارد", "تکمیل سریع"],
  },
  {
    slug: "hakimieh",
    name: "حکیمیه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "توسعه برنامه‌ریزی‌شده، سکونت دانشگاهی و تامین پایدار تاسیسات",
    marketCategory: "planned-residential",
    demandSignals: ["برق ساختمان", "HVAC", "مصالح میان‌رده", "تامین پایدار"],
  },
  {
    slug: "hashtgerd-mehestan",
    name: "شهر جدید هشتگرد و مهستان",
    projectCitySlug: "hashtgerd",
    coverageCitySlug: "karaj",
    focus: "انبوه‌سازی، توسعه برنامه‌ریزی‌شده و تقاضای ویلایی پیرامونی",
    marketCategory: "new-town-volume",
    demandSignals: ["مصالح پایه", "درب استاندارد", "آسانسور پایه", "تاسیسات میان‌رده"],
  },
  {
    slug: "jadeh-makhsous-lashgari",
    name: "جاده مخصوص کرج و لشگری",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "کارخانه‌های پیشرفته، داروسازی، خودروسازی، دفتر-کارخانه و retrofit صنعتی",
    marketCategory: "corporate-industrial",
    demandSignals: ["clean-room HVAC", "امنیت پیشرفته", "کف صنعتی", "شبکه و UPS"],
  },
  {
    slug: "jahan-shahr",
    name: "جهان‌شهر",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "لوکس‌سازی شهری، بازتوسعه قطعه‌ای و فینیشینگ ممتاز",
    marketCategory: "premium-residential",
    demandSignals: ["فینیشینگ ممتاز", "landscape", "آسانسور لوکس", "نما"],
  },
  {
    slug: "jannat-abad-shahr-e-ziba",
    name: "جنت‌آباد و شهر زیبا",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی حجمی، معابر دسترس‌پذیر و فینیشینگ میان‌رده رو به بالا",
    marketCategory: "high-volume-infill",
    demandSignals: ["آسانسور", "BMS پایه", "سنگ و سرامیک", "تاسیسات استاندارد"],
  },
  {
    slug: "jeyhoun-navab",
    name: "جیحون و نواب",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "بافت فرسوده، قطعات کوچک و تامین حجمی اقتصادی",
    marketCategory: "affordable-redevelopment",
    demandSignals: ["مصالح اقتصادی", "درب استاندارد", "لوله‌کشی", "سرامیک میان‌رده"],
  },
  {
    slug: "jordan-nelson-mandela",
    name: "جردن / نلسون ماندلا",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "دفاتر ممتاز، ساختمان‌های پزشکی و سیستم‌های مدیریت ساختمان",
    marketCategory: "premium-corporate-medical",
    demandSignals: ["BMS", "چیلر و VRF", "لابی لوکس", "آسانسور VIP"],
  },
  {
    slug: "kamalshahr-simindasht",
    name: "کمال‌شهر و سیمین‌دشت",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "زیرساخت کارخانه، سوله صنعتی و سیستم‌های ایمنی و کنترل",
    marketCategory: "industrial-expansion",
    demandSignals: ["سوله", "اسکلت فلزی", "BMS صنعتی", "CCTV"],
  },
  {
    slug: "khavaran-pakdasht",
    name: "خاوران و پاکدشت",
    projectCitySlug: "pakdasht",
    coverageCitySlug: "tehran",
    focus: "لجستیک سنگین، مراکز توزیع، کارخانه و زیرساخت صنعتی",
    marketCategory: "logistics-industrial",
    demandSignals: ["کف صنعتی", "سقف صنعتی", "برق فشار قوی", "زیرساخت لجستیک"],
  },
  {
    slug: "kordan",
    name: "کردان",
    projectCitySlug: "kordan",
    coverageCitySlug: "karaj",
    focus: "ویلاهای تفریحی، استخر، محوطه و اتوماسیون",
    marketCategory: "recreational-villa",
    demandSignals: ["استخر", "landscape", "smart home", "مصالح outdoor"],
  },
  {
    slug: "lavasan",
    name: "لواسان",
    projectCitySlug: "lavasan",
    coverageCitySlug: "lavasan",
    focus: "ویلاهای فوق‌لوکس و ساخت سفارشی",
    marketCategory: "hyper-luxury-villa",
    demandSignals: ["متریال لوکس", "smart villa", "استخر", "محوطه‌سازی"],
  },
  {
    slug: "majidieh-bani-hashem",
    name: "مجیدیه و بنی‌هاشم",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی مسکونی متراکم، چرخه سریع خرید، مصالح استاندارد و دسترسی تامین شهری",
    marketCategory: "dense-residential-redevelopment",
    demandSignals: ["HVAC استاندارد", "لوله‌کشی", "آسانسور", "مصالح تکمیل سریع"],
  },
  {
    slug: "marzdaran-zhandarmeri",
    name: "مرزداران و ژاندارمری",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی مسکونی غرب تهران، لجستیک آسان‌تر، نما، مشاعات و تکمیل سریع",
    marketCategory: "premium-mid-volume-residential",
    demandSignals: ["سرامیک ممتاز", "smart home پایه", "آسانسور", "نمای سنگی"],
  },
  {
    slug: "mehrshahr",
    name: "مهرشهر",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "باغ‌شهر، ویلاهای شهری و پروژه‌های کم‌ارتفاع لوکس",
    marketCategory: "garden-city-luxury",
    demandSignals: ["landscape", "فینیشینگ ممتاز", "محوطه", "HVAC لوکس"],
  },
  {
    slug: "mirdamad-zafar",
    name: "میرداماد و ظفر",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "اداری، تجاری، کرتین‌وال و زیرساخت فنی دفتر",
    marketCategory: "corporate-office",
    demandSignals: ["کرتین‌وال", "چیلر و VRF", "نور اداری", "شبکه و امنیت"],
  },
  {
    slug: "mohammad-shahr",
    name: "محمدشهر کرج",
    projectCitySlug: "karaj",
    coverageCitySlug: "karaj",
    focus: "مگاویلا، باغ‌اقامت دائمی، landscape مهندسی، HVAC مستقل و امنیت محیطی",
    marketCategory: "permanent-mega-villa",
    demandSignals: ["HVAC اقامتی", "landscape مهندسی", "امنیت محیطی", "استخر"],
  },
  {
    slug: "narmak",
    name: "نارمک",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "بافت شبکه‌ای، نوسازی سریع و تامین استاندارد حجمی",
    marketCategory: "east-tehran-infill",
    demandSignals: ["سرامیک", "لوله‌کشی", "درب استاندارد", "HVAC"],
  },
  {
    slug: "naziabad-yaqutabad",
    name: "نازی‌آباد و یاقوت‌آباد",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "بازار تجاری-مسکونی پررفت‌وآمد، نوسازی سریع، storefront و مصالح میان‌رده",
    marketCategory: "south-tehran-mixed-use",
    demandSignals: ["storefront", "مصالح میان‌رده", "آسانسور", "امنیت تجاری"],
  },
  {
    slug: "niavaran",
    name: "نیاوران",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "برج‌ویلا، شیب کوهپایه‌ای و اجرای فوق‌لوکس",
    marketCategory: "ultra-luxury-slope",
    demandSignals: ["پایدارسازی", "متریال وارداتی", "نمای لوکس", "smart home"],
  },
  {
    slug: "parand-new-town",
    name: "شهر جدید پرند",
    projectCitySlug: "parand",
    coverageCitySlug: "tehran",
    focus: "مسکن حمایتی، انبوه‌سازی اقتصادی و سفارش‌های تکرارشونده",
    marketCategory: "mass-social-housing",
    demandSignals: ["مصالح پایه", "درب استاندارد", "آسانسور پایه", "نما اقتصادی"],
  },
  {
    slug: "pardis-new-town-tech-park",
    name: "شهر جدید پردیس و پارک فناوری",
    projectCitySlug: "pardis",
    coverageCitySlug: "tehran",
    focus: "مسکن انبوه، تکمیل پروژه‌ها و ساختمان‌های R&D با زیرساخت فنی",
    marketCategory: "new-town-tech",
    demandSignals: ["مصالح انبوه", "HVAC دیتاگرید", "raised floor", "امنیت پیشرفته"],
  },
  {
    slug: "pasdaran",
    name: "پاسداران",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "ساختمان‌های مختلط، نمای تجاری و سیستم‌های هوشمند",
    marketCategory: "premium-mixed-use",
    demandSignals: ["نمای تجاری", "BMS", "امنیت", "retail ground floor"],
  },
  {
    slug: "pirouzi-afsariyeh",
    name: "پیروزی و افسریه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی پرتراکم، قطعات کوچک و تامین اقتصادی تا میان‌رده",
    marketCategory: "affordable-high-density",
    demandSignals: ["درب استاندارد", "لوله‌کشی پایه", "مصالح اقتصادی", "سرامیک"],
  },
  {
    slug: "ponek",
    name: "پونک",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "تجمیع مسکونی، ساخت پرتراکم و تامین حجمی",
    marketCategory: "high-density-infill",
    demandSignals: ["آسانسور", "سرامیک", "HVAC استاندارد", "مصالح حجمی"],
  },
  {
    slug: "roudhen-bomehen",
    name: "رودهن و بومهن",
    projectCitySlug: "roudhen-bomehen",
    coverageCitySlug: "tehran",
    focus: "ویلاسازی کوهپایه‌ای، آپارتمان کم‌ارتفاع و عایق‌کاری اقتصادی",
    marketCategory: "east-corridor-villa",
    demandSignals: ["عایق‌کاری", "گرمایش میان‌رده", "متریال outdoor", "امنیت"],
  },
  {
    slug: "sadeghieh-aryashahr",
    name: "صادقیه و آریاشهر",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "توسعه حمل‌ونقل‌محور، مجتمع‌های مختلط و retrofit تجاری",
    marketCategory: "transit-oriented-mixed-use",
    demandSignals: ["آسانسور", "کف پرتردد", "storefront", "HVAC تجاری"],
  },
  {
    slug: "safadasht-industrial-estate",
    name: "شهرک صنعتی صفادشت",
    projectCitySlug: "safadasht",
    coverageCitySlug: "tehran",
    focus: "سوله، کارخانه، توسعه خطوط تولید، کف صنعتی و زیرساخت تاسیساتی",
    marketCategory: "industrial-estate",
    demandSignals: ["سوله", "کف صنعتی", "تابلو برق", "آتش‌نشانی"],
  },
  {
    slug: "sattarkhan",
    name: "ستارخان",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی سریع، معابر فشرده و تامین میان‌رده",
    marketCategory: "high-turnover-infill",
    demandSignals: ["آسانسور استاندارد", "سرامیک میان‌رده", "HVAC", "لوله‌کشی"],
  },
  {
    slug: "shahr-e-rey-dolatabad",
    name: "شهرری و دولت‌آباد",
    projectCitySlug: "shahr-e-rey",
    coverageCitySlug: "tehran",
    focus: "نوسازی پرتراکم، بافت فرسوده و نماهای اقتصادی قابل اجرا",
    marketCategory: "south-tehran-redevelopment",
    demandSignals: ["نما اقتصادی", "مصالح میان‌رده", "لوله‌کشی", "تکمیل سریع"],
  },
  {
    slug: "shahrak-e-gharb",
    name: "شهرک غرب",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "ویلاهای شهری، بازسازی عمیق و محوطه‌سازی لوکس",
    marketCategory: "urban-villa-renovation",
    demandSignals: ["roofing ممتاز", "landscape", "بازسازی عمیق", "فینیشینگ لوکس"],
  },
  {
    slug: "shahran-koohsar",
    name: "شهران و کوهسار",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "توپوگرافی شیب‌دار، دیوار حائل و برج‌های مسکونی شمال‌غرب",
    marketCategory: "slope-residential",
    demandSignals: ["دیوار حائل", "فونداسیون سنگین", "فینیشینگ میان‌رده رو به بالا", "آسانسور"],
  },
  {
    slug: "shamsabad-industrial-estate",
    name: "شهرک صنعتی شمس‌آباد",
    projectCitySlug: "shamsabad",
    coverageCitySlug: "tehran",
    focus: "سوله‌های بزرگ‌مقیاس، کف صنعتی، برق فشار قوی و زیرساخت تولید",
    marketCategory: "mega-industrial-estate",
    demandSignals: ["سوله بزرگ", "کف صنعتی", "برق صنعتی", "تهویه صنعتی"],
  },
  {
    slug: "shourabad-kahrizak",
    name: "شورآباد و کهریزک",
    projectCitySlug: "kahrizak",
    coverageCitySlug: "tehran",
    focus: "انبار، لجستیک، سردخانه، retrofit صنعتی و امنیت کالا",
    marketCategory: "logistics-cold-storage",
    demandSignals: ["سقف صنعتی", "رکینگ", "CCTV", "آسانسور باربر"],
  },
  {
    slug: "sohanak-ajudaniyeh",
    name: "سوهانک و آجودانیه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "لوکس‌سازی کوهپایه‌ای، گودبرداری حساس و متریال ممتاز",
    marketCategory: "north-east-luxury",
    demandSignals: ["پایدارسازی شیب", "سنگ ممتاز", "پنت‌هاوس لوکس", "smart home"],
  },
  {
    slug: "sohrevardi-seyyed-khandan",
    name: "سهروردی و سیدخندان",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "ساختمان‌های اداری-مختلط، نماهای مدرن و تاسیسات تجاری",
    marketCategory: "administrative-mixed-use",
    demandSignals: ["آسانسور تجاری", "VRF", "کرتین‌وال", "کامپوزیت"],
  },
  {
    slug: "tajrish-dezashib",
    name: "تجریش و دزاشیب",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "بافت تاریخی-لوکس، بازسازی عمیق و لجستیک محدود شمال تهران",
    marketCategory: "historic-premium-renovation",
    demandSignals: ["بازسازی عمیق", "متریال کلاسیک", "لجستیک محدود", "فینیشینگ بوتیک"],
  },
  {
    slug: "tarasht-azadi",
    name: "طرشت و آزادی",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی سریع، مسکن دانشجویی و نیروی کار، retrofit و تامین حجمی",
    marketCategory: "student-workforce-housing",
    demandSignals: ["مصالح استاندارد", "HVAC", "لوله‌کشی", "سرامیک"],
  },
  {
    slug: "tehrandasht-sorkhab",
    name: "تهراندشت و سرخاب",
    projectCitySlug: "tehrandasht",
    coverageCitySlug: "karaj",
    focus: "ویلاسازی زمین تخت، استخر، محوطه و سیستم‌های ویلایی",
    marketCategory: "flat-land-villa",
    demandSignals: ["استخر", "آب‌بندی", "landscape", "smart villa"],
  },
  {
    slug: "tehranpars",
    name: "تهران‌پارس",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "ساخت پرتراکم، سرعت اجرا و تامین میان‌رده حجمی",
    marketCategory: "east-tehran-volume",
    demandSignals: ["مصالح میان‌رده", "تامین حجمی", "HVAC استاندارد", "آسانسور"],
  },
  {
    slug: "tehransar",
    name: "تهرانسر",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "توسعه غرب تهران، مجتمع‌سازی و تامین حجمی میان‌رده",
    marketCategory: "west-tehran-expansion",
    demandSignals: ["تامین حجمی", "برق و HVAC", "مصالح میان‌رده", "آسانسور"],
  },
  {
    slug: "valiasr-enghelab",
    name: "ولیعصر و انقلاب",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "بازسازی عمیق، فضاهای آموزشی، اداری، فرهنگی، retail و محدودیت لجستیکی",
    marketCategory: "central-axis-retrofit",
    demandSignals: ["fit-out تجاری", "عایق صوتی", "HVAC", "نورپردازی"],
  },
  {
    slug: "vanak-sheikh-bahai",
    name: "ونک و شیخ بهایی",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "مجتمع‌های پرتردد، برج‌های اداری و پارکینگ مکانیزه",
    marketCategory: "commercial-tower",
    demandSignals: ["کرتین‌وال", "HVAC تجاری", "پارکینگ مکانیزه", "آسانسور"],
  },
  {
    slug: "velenjak-mahmoudieh",
    name: "ولنجک و محمودیه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "توپوگرافی کوهپایه‌ای، گود عمیق و لوکس‌سازی هوشمند",
    marketCategory: "ultra-luxury-slope",
    demandSignals: ["دیوار حائل", "فونداسیون عمیق", "smart home", "متریال لوکس"],
  },
  {
    slug: "yaftabad-chahardangeh",
    name: "یافت‌آباد و چهاردانگه",
    projectCitySlug: "chahardangeh",
    coverageCitySlug: "tehran",
    focus: "نمایشگاه مبلمان، کارگاه چوب، نورپردازی و حمل کالای حجیم",
    marketCategory: "showroom-workshop",
    demandSignals: ["سازه دهانه‌بلند", "نور تجاری", "شیشه نما", "آسانسور باربر"],
  },
  {
    slug: "yusef-abad-fatemi",
    name: "یوسف‌آباد و فاطمی",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "نوسازی مرکزی، ساختمان‌های اداری-درمانی و retrofit فنی",
    marketCategory: "central-urban-retrofit",
    demandSignals: ["HVAC جایگزین", "آسانسور قابل اتکا", "لوله‌کشی", "بازسازی اداری"],
  },
  {
    slug: "zaferanieh",
    name: "زعفرانیه",
    projectCitySlug: "tehran",
    coverageCitySlug: "tehran",
    focus: "مسکونی لوکس، نمای سنگی و امکانات ممتاز",
    marketCategory: "luxury-residential",
    demandSignals: ["نمای سنگی", "استخر و gym", "smart home", "آسانسور لوکس"],
  },
];

export const projectCityBySlug = new Map(projectCities.map((city) => [city.slug, city]));
export const projectNeighborhoodBySlug = new Map(projectNeighborhoods.map((neighborhood) => [neighborhood.slug, neighborhood]));

export function getProjectCityBySlug(slug: string) {
  return projectCityBySlug.get(slug);
}

export function getProjectNeighborhoodsByProjectCity(citySlug: string) {
  return projectNeighborhoods.filter((neighborhood) => neighborhood.projectCitySlug === citySlug);
}

export function getProjectNeighborhoodsByCoverageCity(citySlug: CitySlug) {
  return projectNeighborhoods.filter((neighborhood) => neighborhood.coverageCitySlug === citySlug);
}

export function getProjectCitiesByCoverageCity(citySlug: CitySlug) {
  const usedCitySlugs = new Set(
    getProjectNeighborhoodsByCoverageCity(citySlug).map((neighborhood) => neighborhood.projectCitySlug),
  );

  return projectCities.filter((city) => usedCitySlugs.has(city.slug));
}
